client_id = 'KOqhggnyUeMNognvAyuybROJ1U12AxSKPVABMUpo'
redirect_uri = 'http://localhost:14396'
BASE_URL = 'http://gymkhana.iitb.ac.in/sso/'
API_URL = BASE_URL + 'user/api/user/'
OAUTH_URL = BASE_URL + 'oauth/authorize/'
